version: "3.3"

services:
  # MySQL
  db:
    platform: linux/x86_64
    container_name: "db"
    # path配下のDockerfile読み込み
    build: ./docker/mysql
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: pdf2excel_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./log/mysql:/var/log/mysql # ログの保存
    networks:
      - local-net
    
  s3:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: s3
    env_file:
      - env_file.env
    volumes:
      - ./volumes/minio:/data
      - ./docker/minio/policies:/policies
    ports:
      - "9000:9000"
    command: ["--compat", "server", "/data"]
    networks:
        - local-net

  # FastAPI
  api:
    platform: linux/x86_64
    container_name: api
    env_file:
      - env_file.env
    # db起動後に立ち上げる
    depends_on:
      - db
      - s3
    command: >
      sh -c "sh ./wait_for_mysql.sh && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    # path配下のDockerfile読み込み
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/server
    networks:
      - local-net

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge